### ISSUE TITLE
Install GameClock

### ISSUE THREAD

**Issue by pythonjmc** [krishNav-eng/SudukuGame#1]
Hi, in your code you imported GameClock, so i tryed to install it by: pip install GameClock, but it told me: 'ERROR: Could not find a version that satisfies the requirement GameClock (from v
ersions: none)
ERROR: No matching distribution found for GameClock'

How must i do ?

**Comment by pythonjmc** [comment]
@krishNav-eng Your sudoku game is amazing ! GG !

**Comment by krishNav-eng** [comment]
> @krishNav-eng Your sudoku game is amazing ! GG !

Glad to know that you liked it!
If you want some other features, feel free to tell me.
